### ISSUE TITLE
Add link to spec from README/repo

### ISSUE THREAD

**Issue by domenic** [WICG/page-lifecycle#17]
At least from the readme. If you have permissions, also from the repository header.

**Comment by spanicker** [comment]
I added link to spec at the top of the readme.
I'm not sure what it means to "link from repository header" - any pointer?

BTW - do you think web-lifecycle is a reasonable name? It's a bit generic / ambiguous I think. Would "page-lifecycle" be better?

**Comment by domenic** [comment]
Looks good! The repository header is where it currently says "No description, website, or topics provided." See e.g. https://github.com/domenic/async-local-storage where there's a link to the spec. But, I think we probably don't have permissions to change that.

I kind of like the idea of renaming, perhaps document lifecycle to be more precise? I dunno though, we prefix a lot of specs with "web".

**Comment by spanicker** [comment]
Updated repo header, thanks.

Regarding the naming -- I was thinking that we kind of want to capture the full document tree -- internally we use "Page" for that concept, so not sure if "Page Lifecycle" is meaningful to folks beyond Chrome people.
Document sounds a bit too specific, and also has a different meaning in Blink (includes layout, paint etc):
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/dom/document_lifecycle.h

**Comment by spanicker** [comment]
Renamed.
