### ISSUE TITLE
Specific task source discussions

### ISSUE THREAD

**Issue by domenic** [WICG/page-lifecycle#20]
https://github.com/WICG/page-lifecycle/commit/5c4e015102e6743343915294362460d38ee3b6a7 started fleshing out the freezable task sources.

The timer task source exists: https://html.spec.whatwg.org/#timer-task-source

But I don't believe any specification defines the "loading" task source.

Is this the same as the [networking task source](https://html.spec.whatwg.org/#networking-task-source)? Click on the `<dfn>` to see all its usage sites in HTML. It is also notably used [in fetch](https://fetch.spec.whatwg.org/#queue-a-fetch-task), i.e. basically every fetch goes through here. Was that the intention, or was it supposed to be more scoped?

**Comment by panickers** [comment]
Sorry for the delay!
Yes "Loading" task source is same as "networking" task source.
