### ISSUE TITLE
Friendly TAG review: Nit: Rendering issue in spec

### ISSUE THREAD

**Issue by kenchris** [WICG/page-lifecycle#21]
in response to https://github.com/w3ctag/design-reviews/issues/283 :

I see the rendering `%5Bpage-lifecycle%5D` which I assume should be `[page-lifecycle]`

**Comment by kenchris** [comment]
Other minor hits is that some list items start with upper case and others don't

Also, I think writing end user as end-user makes it a bit more readable

**Comment by kenchris** [comment]
Any update, is this fixed?

**Comment by spanicker** [comment]
@tabatkins to comment on the

**Comment by tabatkins** [comment]
Hm, for some reason the webperf boilerplate just copied over the same code from the url into the plain text content. URL-escaping isn't the same as HTML-escaping!

Fixed in 4bf87fa
