### ISSUE TITLE
Friendly TAG review: Nit: freeze vs resume

### ISSUE THREAD

**Issue by kenchris** [WICG/page-lifecycle#22]
in response to w3ctag/design-reviews#283 :

When you freeze something you normally **thaw** it. When something is resumed, it was usually **suspended** before.

I think the names could be a bit more aligned

**Comment by kenchris** [comment]
Any update?

**Comment by spanicker** [comment]
We've spent a huge amount of time bikeshedding the names (the reaction to "thaw" was mixed, suspend was already taken) both at last TPAC and internally, so we have to stop at some point :)
This came in too close to shipping and I didn't think it was worth slipping for this, I would have loved to receive this feedback in the first TAG review here: 
https://github.com/w3ctag/design-reviews/issues/205
