### ISSUE TITLE
Life Cycle Breaks Interaction

### ISSUE THREAD

**Issue by mischmerz** [WICG/page-lifecycle#41]
I have a multitude of issues with this intervention. I realize that my clout here is limited, but please hear me out. I've been developing web services since the beginning of the web. It has been a blast to experience how the web went from the static display of pages to the fully interactive environments we are seeing today. 

This proposal is like turning the clock back 10 years. Plenty of sites, including mine, are relying on interactivity e.g. websockets or long polls to get the job done. because (web-) push is often annoying and a significant number of users are rejecting the request to send push anyway. 

Take one of my system as an example: It's a web-rtc 'Skype'  type service that sits on a page or in a web-app and waits for calls. 

An incoming call is signaled through websockets so that the client can start to negotiate the web-rtc connection. This won't work anymore if the page (or web-app) is frozen. Push wouldn't help either: The notification is easily overlooked (especially if not a the desk) and the service worker can't send a message to the app because the app is frozen. Even if the notification would be noticed, the user would now have to go through all of his tabs to find the right one. Other interactive services like e.g. web-chats will have the same problem: Should we really send a pop-up web-push for all incoming chat messages, emails or breaking news? Wouldn't it be much better to let the web-sites handle this and e.g. change the tab title to reflect that updates have been made?

Javascript is so powerful nowadays that it is used to process things client side. I could give you literally dozens of cases were objects are processed client side based on events that are transmitted to the browser. Surveillance, home automation, industrial and medical applications rely on events emitted from a variety of devices that may not even be stored server side. The EEG image may simply be lost if the operator decides to browse the news while the application is running.  

Additionally, I find it troublesome that this proposal ties every interactive (well - those sites that want to remain interactive) web-site into the Google universe. This is not the way the web was meant to be. There needs to remain at least one non-Google way to be able to notify the browser. 

If you really feel the need to save CPU power on desktops or laptops (which I find highly unnecessary and intrusive), go ahead and block all network access except websockets. Or limit network access to 10 bytes a second. Disallow outgoing network traffic. Block rapid changes to the DOM. Limit CPU usage. Whatever you do: Do NOT completely freeze a site. This may not only be dangerous, but it will also kill the interactive web as we know it.

Thanks for reading.

Michaela

**Comment by domenic** [comment]
Hi Michaela,

There seems to be some misunderstanding here. Page Lifecycle does not do any of the things you're alleging.

User agents already aggressively freeze pages. For example, from talking to Safari engineers, the intent on iOS is that all tabs except for 1 are frozen, and all tabs are frozen entirely when Safari is not the active app. I came back to my Firefox install this morning, and all tabs except the current one were "grayed out", which I assume means they are not running any code. (When I focus them they need to get reloaded.) Etc. This is common in web browsers and has been happening for years.

What the Page Lifecycle spec does is formalize this behavior, and crucially, _add functionality for web pages to get notified about it_, which was not previously possible. So it's actually meant to help these kinds of situations be easier for web applications to deal with. It doesn't have much to do with any of the things you're discussing.

Since this appears to not be very related to the spec, and certainly doesn't point to any bug in the spec text (which is what we use the issue tracker for), I'll close this. However, you're welcome to continue discussing in the closed thread. I'll just say that messages that are actually about the spec text are more likely to get a response than off-topic ones.

Thanks,
Domenic

**Comment by asutherland** [comment]
To elaborate on the current Firefox UX around tab unloading and session restoring: Pinned tabs always get restored at session restore time and don't get unloaded.  To restate that another way: the way a user conveys their intent that they always want a tab to be running is to pin a tab.

**Comment by mischmerz** [comment]
First - we're not talking Firefox, we're talking Chrome. Second: Even after about two hours, all tabs remained active in Firefox on Linux.  Just tested it  - though this may have changed in the latest version. 

I find it presumptuous for all browser developers to unilaterally decide to freeze, kill, unload or otherwise prohibit a valid and well behaved website from working properly. What's next? Automatically remove legal content because it might be offensive for  some viewers? If a web-developer uses websockets or long polling to keep a web-site alive, why would you, without any consent and with disregard to the possibly damaging consequences, decide to stop this site from working? 

Do you really think this is the way the web should behave? People have trusted in the web as a communications platform. The have invested significant amounts of resources into their web-services and in the standards that govern those services. 

And now folks come along and toss them for no good reason.

You were the guardians of 'our' web. I am extremely disappointed in your leadership and in your refusal to modify this 'freezing' / 'unloading' so that the web-developers are able to maintain at least some control over their services and users.

Michaela

**Comment by domenic** [comment]
Hi Michaela,

Again there seems to be some confusion here. We're on the issue tracker for the spec, not for Chrome. The issue tracker for Chrome is at https://crbug.com/.

**Comment by mischmerz** [comment]
Domenic - the spec has been written by Chrome employees or am I wrong? I find it telling though that the answer to my sincere thoughts is a organizational advise.

**Comment by domenic** [comment]
That is true. However, when you want to communicate your feelings about a product feature some engineers have worked on (freezing background tabs), it's not a great strategy to go find a web standard that those engineers colleagues have contributed to, and post on that standard's issue tracker. Especially when that standard is specifically about making that product feature more developer friendly, as explained above .

**Comment by mischmerz** [comment]
Domenic: As we (non W3C-member) web-developers are rarely invited to discuss planned web-technologies, we don't really have a meaningful way to let y'all know what we think about an issue. So we have to find ourselves outlets to transmit our thoughts - after all - we are engineers too. I have written about this subject in other forums too. 

But let's talk about this web-standard. It is, as is the underlying technology, deeply problematic. It codifies a behavior that is unacceptable in the first place. If web standards can be tossed or fundamentally changed without a very broad consensus, it completely erodes the trust in those standards. Browser developers may do as they please, but any proposed W3C standard should not just rubber stamp what a few engineers came up with. Backwards compatibility should always be considered as should the potential impact of the web community at large. Never before has any proposed standard interrupted the functionality of the web as this standard does.

Freezing or discarding tabs should be requested by the underlying operating system. Because there's simply no reason to freeze or unload tabs on any computer that has plenty of battery power and other resources.

Finally: It's not the browser developers who make the web, it's the web-developers. We have created web-sites long before there even was Chrome, Safari or Mozilla. It is sad how some folks are now trying to monopolize everything we worked for over the last 20+ years.

Michaela
